-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\hasan_000\Desktop\NTNU\Thesis\BPT\codegen\call_exp\hdlsrc\call_exp_fixpt_pkg.vhd
-- Created: 2020-06-19 20:10:56
-- 
-- Generated by MATLAB 9.6, MATLAB Coder 4.2 and HDL Coder 3.14
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE call_exp_fixpt_pkg IS
  TYPE vector_of_unsigned14 IS ARRAY (NATURAL RANGE <>) OF unsigned(13 DOWNTO 0);
END call_exp_fixpt_pkg;

